### ISSUE TITLE
[hax editor] Page with tags yields implode is not defined ReferenceError

### ISSUE THREAD

**Issue by whatsacomputertho** [haxtheweb/issues#2065]
I added a few tags to my page, and this ended up leading to a crash when saving the page.

```
open: http://localhost:3000
.\node_modules\@haxtheweb\haxcms-nodejs\dist\lib\RSS.js:51
        tags = implode(',', item.metadata.tags);
        ^

ReferenceError: implode is not defined
    at FeedMe.rssItems (.\node_modules\@haxtheweb\haxcms-nodejs\dist\lib\RSS.js:51:9)
    at FeedMe.getRSSFeed (.\node_modules\@haxtheweb\haxcms-nodejs\dist\lib\RSS.js:24:10)
    at HAXCMSSite.updateAlternateFormats (.\node_modules\@haxtheweb\haxcms-nodejs\dist\lib\HAXCMS.js:622:61)
    at HAXCMSSite.updateNode (.\node_modules\@haxtheweb\haxcms-nodejs\dist\lib\HAXCMS.js:1343:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.saveNode (.\node_modules\@haxtheweb\haxcms-nodejs\dist\routes\saveNode.js:278:11)

Node.js v20.15.1
```

**Comment by btopro** [comment]
missed a reference; at some point need to go back and remove locutus but time in day issue.
