### ISSUE TITLE
Cannot start desktop app on debian stable

### ISSUE THREAD

**Issue by singpolyma** [haxtheweb/issues#2128]
```
$ npm run start

> haxtheweb-desktop@9.0.6 start
> npm run build && electron .


> haxtheweb-desktop@9.0.6 build
> babel src --out-dir dist/src --copy-files --include-dotfiles

Successfully compiled 5 files with Babel (272ms).
App threw an error during load
Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/home/singpolyma/src/hax-desktop/node_modules/sharp/lib/sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/singpolyma/src/hax-desktop/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/home/singpolyma/src/hax-desktop/node_modules/sharp/lib/sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/singpolyma/src/hax-desktop/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
```

Running `npm install sharp` or any of the suggested commands in the error does not help, still get the same error.

**Comment by btopro** [comment]
Did you try to commands that compile for debian in package json? Ill have to check when I get to a desktop but I haven't experienced this issue previously in doing builds for desktop

**Comment by singpolyma** [comment]
Turns out I get this even with just the `npx` command, so I think npm 10+ is needed for the sharp dependency

**Comment by btopro** [comment]
https://www.npmjs.com/package/sharp might be right there

**Comment by btopro** [comment]
I think you might be correct. NPM 10.7.0 comes packaged which both npx and desktop commands have

```
"engines": {
        "node": ">=18.20.3"
    },
```

**Comment by singpolyma** [comment]
If I package the desktop app elsewhere and then install it here, will it bundle the nodejs it needs, or does it depend on the system one? I'm never sure with electron stuff

**Comment by btopro** [comment]
I have to imagine it will bundle based on the version present when the script runs on the architecture in question. https://github.com/haxtheweb/desktop/blob/master/package.json#L33

I'm not an electron expert but I believe we still need a workflow to automate the packaging across environments as I have one written to do windows but it never finishes on my machine when I try it (I also don't have windows so not sure if it works there) at some point I'd love a build pipeline for updating and distributing the desktop version as it's just a wrapper and minor API routing on top of the npx command for haxcms-nodejs
