### ISSUE TITLE
[desktop] Do more work / testing on OSX version

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2158]
In running it on Bill's laptop it got most of the way to working but complained about firewall (to be expected) and then wouldn't communicate to the main window to open the app.

```js
Error: Attempted to register a second handler for 'get-express-app-url'
at IpcMainImpl.handle (node:electron/js2c/browser_init:2:101629)
at createWindow (/Applications/haxtheweb-desktop.app/Contents/Resources/app/dist/src/main.js:64:21)
at App.<anonymous> (/Applications/haxtheweb-desktop.app/Contents/Resources/app/dist/src/main.js:85:63)
at App.emit (node:events:519:28)
```

**Comment by btopro** [comment]
## Implementation plan

> Drafted via the HAX Issue Research workflow — proposed for review; not yet posted to the issue.

**Issue:** https://github.com/haxtheweb/issues/issues/2158
**Repo / surface:** `desktop` (Electron main process) — `src/main.js`

### Problem statement
On macOS, the HAX desktop (Electron) app fails to open its window content. After startup, it throws `Error: Attempted to register a second handler for 'get-express-app-url'` and the renderer never loads the Express app URL ("wouldn't communicate to the main window to open the app"). The firewall prompt is expected and out of scope; the blocker is the IPC double-registration crash. Scope is limited to fixing this crash.

### Current state / context
The Electron main process lives in `desktop/src/main.js` (Babel-transpiled to `dist/src/main.js`, which matches the stack trace in the issue).

- `createWindow()` (`desktop/src/main.js:41`) creates the `BrowserWindow`, wires up window event listeners, then registers three `ipcMain.handle()` channels:
  - `desktop/src/main.js:70` — `ipcMain.handle("get-express-app-url", () => expressAppUrl)`
  - `desktop/src/main.js:71` — `ipcMain.handle('dark-mode:toggle', ...)`
  - `desktop/src/main.js:80` — `ipcMain.handle('dark-mode:system', ...)`
  - `desktop/src/main.js:83` — `mainWindow.loadURL(...)` runs **after** the handler registrations.
- `createWindow()` is called from two places:
  - `desktop/src/main.js:92` — inside `app.whenReady().then(...)` (first window).
  - `desktop/src/main.js:95` — inside `app.on("activate", ...)` with guard `if (BrowserWindow.getAllWindows().length === 0) createWindow();`
- On macOS (`process.platform === "darwin"`), `window-all-closed` does **not** quit the app (`desktop/src/main.js:86-87`). When all windows are closed and the user reactivates the app (dock click), `activate` fires, the window count is 0, and `createWindow()` runs again.
- `ipcMain.handle()` may only be called **once per channel** for the lifetime of the app (Electron constraint). The second `createWindow()` call re-invokes `ipcMain.handle("get-express-app-url", ...)` at line 70 and throws. Because the throw happens **before** `mainWindow.loadURL()` (line 83), the newly created window is blank — matching the "wouldn't communicate to the main window to open the app" symptom. `dark-mode:toggle` and `dark-mode:system` would throw on the same second call, but `get-express-app-url` fails first.
- The renderer invokes the channel via `desktop/src/preload.js:4` — `getExpressAppUrl: () => ipcRenderer.invoke("get-express-app-url")`. No change needed on the renderer/preload side.

### Proposed approach
1. Extract the three `ipcMain.handle()` registrations out of `createWindow()` into a new `registerIpcHandlers()` function in `desktop/src/main.js`. These handlers only reference module-level/app-lifetime values (`expressAppUrl` from `desktop/src/main.js:9` and the imported `nativeTheme`), so they are safe to register once and do not depend on `mainWindow`.
2. Call `registerIpcHandlers()` exactly once inside the existing `app.whenReady().then(...)` block (`desktop/src/main.js:90`), alongside the existing `registerGlobalShortcuts()` call at line 91 and before `createWindow()` at line 92.
3. Remove the three `ipcMain.handle(...)` calls (lines 70, 71-78, 80-82) from `createWindow()`, leaving window creation, event listeners, and `mainWindow.loadURL()` (line 83) in place. This guarantees handlers register once regardless of how many times `createWindow()` runs.
4. Rebuild the desktop app (`npm run build` in the `desktop` repo — this is the desktop's own Babel build `babel src --out-dir dist/src`, not the webcomponents monorepo build) and verify on macOS that: (a) the app launches and loads the Express app URL, and (b) closing all windows then reactivating via the dock no longer throws and reopens the window correctly.

### Files likely affected
- `desktop/src/main.js` — move three `ipcMain.handle()` calls out of `createWindow()` into a one-time `registerIpcHandlers()` called from `app.whenReady()`.

### Considerations / risks
- **No optional chaining (`?.`)** will be used in the change (per toolchain constraint).
- This is Electron **main process** code — DDD design system, WCAG/accessibility, HAXSchema, and OER Schema considerations do not apply here (no web component / renderer UI changes).
- No new web components are introduced, so the `hax webcomponent` CLI rule does not apply.
- This is the `desktop` repo's own Babel build, **not** the webcomponents top-level monorepo build; the "no top-level monorepo build" rule is not violated.
- The fix is low-risk: the handlers are idempotent and reference only app-lifetime values, so moving them earlier in the lifecycle has no behavioral change beyond preventing the duplicate-registration crash.
- Verification requires macOS (the reported environment); the agent cannot test on OSX directly, so step 4 above should be run by the reporter/maintainer on a Mac.

### Open questions
(none — scope confirmed as the IPC double-registration crash fix only)

_Plan drafted with Oz via the HAX Issue Research skill._
